#6 Update state depends on the userRole
fac-15/the-real-junk-food-project pull request #35
Opened 2019-02-14 16:45 UTC by Whooolia

2019-02-14 17:02 UTC, Jbarget requested changes

2019-02-14 17:02 UTC, Jbarget commented on src/component/form/form.js
> +    userRole: "driver"
lets put the userRoles into constants. Constants are typically defined in a constants file and are all uppercase:

in `src/constants/userRoles.js`:

```
export const DRIVER = 'DRIVER'
export const SUPPLIER = 'SUPPLIER
```

then, anytime you need to refer to a driver you import the constant and use it, not sure what the other user roles are but put them into constants too :)

2019-02-14 17:02 UTC, Jbarget commented on src/component/form/form.js
> +    // const value = target.type === 'radio' ? target.id : target.value
can we get rid of this?

2019-02-14 17:02 UTC, Jbarget commented on src/component/form/form.js
>    handleChange = event => {
```
handleChange = { target } => {
	this.setState({...})
}
```

2019-02-14 17:13 UTC, Oliversw commented on src/component/form/form.js
>    handleChange = event => {
Ohh I love this!

2019-02-14 17:24 UTC, Oliversw commented on src/component/form/form.js
> +    userRole: "driver"
Could you please explain more why we would benefit from using this? We actually only have the two user roles, and I don't think that we need to refer to them in too many places.

2019-02-14 17:31 UTC, Jbarget commented on src/component/form/form.js
> +    userRole: "driver"
this is something that is so easy to implement at the beginning but if you want to implement further down the line its a lot harder. So its not just about whats needed right now

There's a phrase in coding called "single source of truth". As a general rule always always always have a single source of truth for something. So in this case wherever you refer to the user being a `DRIVER` or a `SUPPLIER` it always comes from one place

2019-02-14 17:36 UTC, Oliversw commented on src/component/form/form.js
> +    userRole: "driver"
Oh okay! So in that case every constant that we create throughout the app would be contained in that file?

2019-02-14 17:37 UTC, Whooolia commented
The last commit is about authentication. Now It's fully functional authentication for drivers and suppliers! :+1: Updates state with the data we got back from Airtable or it gives false if the data is not matched to Airtable

2019-02-14 18:02 UTC, Jbarget commented on src/component/form/form.js
> +    userRole: "driver"
"would be contained in that file" do you mean folder?

`src/constants/...`

2019-02-15 10:50 UTC, charlielafosse commented on src/component/form/form.js
> +    userRole: "driver"
Hey I think we've correctly implemented this now! Just pushed up

2019-02-15 10:51 UTC, merged